name: CiCd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Python dependencies
      - name: Install Python packages
        run: make python install
      - name: Python lint
        run: make -C python lint
      - name: Python test
        run: make -C python test
      - name: Python format
        run: make -C python format

      # Build and run the Rust code
      - name: Build Rust
        run: make -C rust build
      - name: Run Rust
        run: make -C rust run

      # Deploy or perform other actions if needed
      - name: Deploy
        run: make -C python deploy
